/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as CropRecommendationRouteImport } from './routes/crop-recommendation'
import { Route as IndexRouteImport } from './routes/index'

const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRecommendationRoute = CropRecommendationRouteImport.update({
  id: '/crop-recommendation',
  path: '/crop-recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/disease-detection': typeof DiseaseDetectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/disease-detection': typeof DiseaseDetectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crop-recommendation': typeof CropRecommendationRoute
  '/disease-detection': typeof DiseaseDetectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crop-recommendation' | '/disease-detection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crop-recommendation' | '/disease-detection'
  id: '__root__' | '/' | '/crop-recommendation' | '/disease-detection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropRecommendationRoute: typeof CropRecommendationRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-recommendation': {
      id: '/crop-recommendation'
      path: '/crop-recommendation'
      fullPath: '/crop-recommendation'
      preLoaderRoute: typeof CropRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropRecommendationRoute: CropRecommendationRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
